config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do 
	  get '/auth', to: 'devise/sessions#new', as: :auth
	  get '/login', to: 'devise/sessions#new', as: :login
	  get '/logout', to: 'devise/sessions#destroy', as: :logout
	  match "/confirm", to: "users/confirmations#confirm", via: [:get, :post, :patch] #as: :confirm
  end
      
  devise_for :users, controllers: {
    users: 'users/sessions',
    :passwords => 'users/passwords',
    :registrations => 'users/registrations',
    :confirmations => 'users/confirmations'
  }
  

   root 'welcome#index'
   get '/', to: 'welcome#:index', as: :home
   get '/profile', to: 'profile#new', as: :profile
   get '/edit_profile', to: 'profile#edit', as: :edit_profile
   put '/edit_profile', to: 'profile#update', as: :update_profile
   get '/change_password', to: 'profile#change_password', as: :change_password
   

   namespace :admin do
   	 get '/', to: 'base#index', as: :home
     resources :chapters
     resources :convention_events
     resources :countries
     resources :members
     resources :payment_purposes
     resources :payments
     resources :photos
     resources :projects
     resources :states
     resources :users
     resources :zips
   end
   get '/:action', to: 'welcome#:action'
   
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to	:updated_by, class_name: :user
	belongs_to :album
	# Photo uploader using carrierwave
	mount_uploader :image, PhotoUploader
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::BaseController
  expose(:photo) {Photo.find_by_id(params[:id]) || Photo.new}
  
  # POST /admin/photos
  # POST /admin/photos.json
  def create
    photo.attributes = photo_params

    respond_to do |format|
      if photo.save
        format.html { redirect_to admin_photos_path, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: photo }
      else
        format.html { render :new }
        format.json { render json: photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/photos/1
  # PATCH/PUT /admin/photos/1.json
  def update
    respond_to do |format|
      if photo.update(photo_params)
        format.html { redirect_to admin_photo_path(photo), notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: photo }
      else
        format.html { render :edit }
        format.json { render json: photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/photos/1
  # DELETE /admin/photos/1.json
  def destroy
    photo.destroy
    respond_to do |format|
      format.html { redirect_to admin_photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params[:photo]
    end
end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/views/admin/photos/_form.html.haml
= form_for @admin_photo do |f|
  - if @admin_photo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_photo.errors.count, "error")} prohibited this admin_photo from being saved:"
      %ul
        - @admin_photo.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/admin/photos/edit.html.haml
%h1 Editing admin_photo

= render 'form'

= link_to 'Show', @admin_photo
\|
= link_to 'Back', admin_photos_path

app/views/admin/photos/index.html.haml
%h1 Listing photos

%table{id: 'admin_photos', style: "width: 100%;"}
  %thead
    %tr
      %th
      %th
      %th
      
  %tbody
    - photos.each do |admin_photo|
      %tr
        %td= link_to 'Show', admin_photo
        %td= link_to 'Edit', edit_admin_photo_path(admin_photo)
        %td= link_to 'Destroy', admin_photo, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Photo', new_admin_photo_path

app/views/admin/photos/new.html.haml
%h1 New admin_photo

= render 'form'

= link_to 'Back', admin_photos_path

app/views/admin/photos/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_photo_path(@admin_photo)
\|
= link_to 'Back', admin_photos_path