config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do 
	  get '/auth', to: 'devise/sessions#new', as: :auth
	  get '/login', to: 'devise/sessions#new', as: :login
	  get '/logout', to: 'devise/sessions#destroy', as: :logout
	  match "/confirm", to: "users/confirmations#confirm", via: [:get, :post, :patch] #as: :confirm
  end
      
  devise_for :users, controllers: {
    users: 'users/sessions',
    :passwords => 'users/passwords',
    :registrations => 'users/registrations',
    :confirmations => 'users/confirmations'
  }
  

   root 'welcome#index'
   get '/', to: 'welcome#:index', as: :home
   get '/profile', to: 'profile#new', as: :profile
   get '/edit_profile', to: 'profile#edit', as: :edit_profile
   put '/edit_profile', to: 'profile#update', as: :update_profile
   get '/change_password', to: 'profile#change_password', as: :change_password
   

   namespace :admin do
   	 get '/', to: 'base#index', as: :home
     resources :chapters
     resources :convention_events
     resources :countries
     resources :members
     resources :payment_purposes
     resources :payments
     resources :photos
     resources :projects
     resources :states
     resources :users
     resources :zips
   end
   get '/:action', to: 'welcome#:action'
   
end

app/views/shared/_admin_header.haml
#header
	Logged in as: 
	= link_to current_user.name, admin_user_path(current_user)
	= link_to 'logout', logout_path
	.time-auth-search
		.left-tas.fleft
			.pss-time.fleft
				- Time.use_zone("West Central Africa") do |z|
					= Time.zone.now.strftime('%I:%M %p %Z')
				,
				%b PSS
			.usa-time.fleft
				= Time.now.strftime('%I:%M %p %Z')
				,
				%b USA
				.clear
				.fleft
			.clear
		.clear
	.admin_top-menu
		%table{:cellpadding => "0", :cellspacing => "0", :width => "100%"}
			%tr
				%td{:width => "117"}
					= link_to 'Home', '/', class: "#{ 'selected' if request.path == '/'}"
				%td
					= link_to 'users', '/admin/users/', class: "#{ 'selected' if controller.controller_name == 'users'}"
				%td
					= link_to 'members', '/admin/members/', class: "#{ 'selected' if controller.controller_name == 'members'}"
				%td
					= link_to 'chapters', '/admin/chapters/', class: "#{ 'selected' if controller.controller_name == 'chapters'}"
				%td
					= link_to 'projects', '/admin/projects/', class: "#{ 'selected' if controller.controller_name == 'projects'}"
				%td
					= link_to 'payment purposes', '/admin/payment_purposes/', class: "#{ 'selected' if controller.controller_name == 'payment_purposes'}"
				%td
					= link_to 'payments', '/admin/payments/', class: "#{ 'selected' if controller.controller_name == 'payments'}"
				%td
					= link_to 'photos', '/admin/photos/', class: "#{ 'selected' if controller.controller_name == 'photos'}"
				%td
					= link_to 'countries', '/admin/countries/', class: "#{ 'selected' if controller.controller_name == 'countries'}"
				%td
					= link_to 'profile', '/profile', class: "#{ 'selected' if request.path == '/profile'}"
				%td{:width => "105"}
					= link_to 'convention events', '/admin/convention_events/', class: "last #{ 'selected' if controller.controller_name == 'convention_events'}"
					

app/views/shared/_admin_user_form.html.haml
%td
	.span3{style: "width: 100%;"}
		.reg-col
			Personal Information
		.admin_panel_inner
			.row-fluid
				= f.label 'first_name', 'First Name*', class: "control-label", required: true
				= f.text_field :first_name, tabindex: 1, class: 'span12', maxlength: 20, required: true
			.row-fluid
				= f.label 'middle_name', 'Middle Name', class: "control-label"
				= f.text_field :middle_name, tabindex: 2, class: 'span12', maxlength: 20
			.row-fluid
				= f.label 'last_name_pss', 'Last (or Surname) Name (PSS)*', class: "control-label", required: true
				= f.text_field :last_name_pss, tabindex: 3, class: 'span12', maxlength: 20, required: true
			.row-fluid
				= f.label 'last_name_now', 'Last (or Surname) Name (Now)*', class: "control-label", required: true
				= f.text_field :last_name_now, tabindex: 4, class: 'span12', maxlength: 20, required: true
			.row-fluid
				= f.label 'class_year', 'Class Of', class: "control-label"
				= f.select :class_year, (1983..Date.today.year).to_a, {include_blank: '--Please Select--'}, tabindex: 5, class: 'span12'
			.row-fluid
				= f.label 'gender', 'Gender*', class: "control-label", required: true
				= f.select :gender, ['female', 'male'], {include_blank: '--Please Select--'}, tabindex: 6, class: 'span12', required: true
%td
	.span3{style: "width: 100%;"}
		.reg-col
			Contact Information
		= f.fields_for address do |a|
			.admin_panel_inner
				.row-fluid
					= a.label 'country_id', 'Country*', class: "control-label", required: true
					= a.select :country_id, countries.map{|c| [c.name, c.id]}, {include_blank: '--Please Select--'}, tabindex: 8, class: 'span12', required: true
				.row-fluid
					= a.label 'state_id', 'State*', class: "control-label"
					= a.select :state_id, states.map{|c| [c.name, c.id]}, {include_blank: '--Please Select--'}, tabindex: 9, class: 'span12', required: true
				.row-fluid
					= a.label 'street1', 'Address Line 1*', class: "control-label", required: true
					= a.text_field :street1, tabindex: 10, class: 'span12', maxlength: 30, required: true
				.row-fluid
					= a.label 'street2', 'Address Line 2', class: "control-label"
					= a.text_field :street2, tabindex: 11, class: 'span12', maxlength: 20
				.row-fluid
					= a.label 'city', 'City*', class: "control-label", required: true
					= a.text_field :city, tabindex: 12, class: 'span12', maxlength: 20, required: true
				.row-fluid
					= a.label 'zip', 'Zip*', class: "control-label", required: true
					= a.text_field :zip, tabindex: 13, class: 'span12', maxlength: 20, required: true
%td{style: "width: 33%;"}
	.span3{style: "width: 100%;"}
		.reg-col
			Membership Information
		.admin_panel_inner
			.row-fluid
				= f.label 'phone', 'Cell Phone', class: "control-label"
				= f.text_field :phone, tabindex: 14, class: 'span12', maxlength: 75
			.row-fluid
				= f.label 'full_time_student', 'Full Time Student*', class: "control-label", required: true
				= f.select :full_time_student, [['No', false],['Yes', true]], {include_blank: '--Please Select--'}, tabindex: 15, class: 'span12', required: true
			.row-fluid
				= f.label 'profession', 'Profession', class: "control-label"
				= f.text_area :profession, tabindex: 16, class: 'span12', maxlength: 75
			.row-fluid
				= f.label 'chapter_id', 'Chapter', class: "control-label"
				= f.select :chapter_id, all_chapters.map{|c| [c.name, c.id]}, {include_blank: '--Please Select--'}, tabindex: 17, class: 'span12'
			.row-fluid
				= f.label 'username', 'Login (min. 3 characters)*', class: "control-label", required: true
				= f.text_field :username, tabindex: 18, class: 'span12', minlength: 3, maxlength: 25, required: true
			.row-fluid
				= f.label 'email', 'Email*', class: "control-label", required: true
				= f.text_field :email, tabindex: 19, class: 'span12', maxlength: 75, required: true

app/views/shared/_footer.haml
- footer_class = current_user ? 'auth-footer' : ''
#footer{class: footer_class }
	.footer-center
		.bottom-menu.fleft
			%ul
				- if can? :read, :admin #current_user && (current_user.admin? || current_user.super_admin?)
					%li= link_to 'Admin', admin_home_path
				%li
					%a.selected{:href => "/"} Home
				%li
					%a{:href => "/about_us/"} About us
				%li
					%a{:href => "/donations/"} Donations
				%li
					%a{:href => "/projects/"} Projects
				%li
					%a{:href => "/contact_us/"} Contact us
				%li
					%a{:href => "/terms_of_use/"} Terms of use
				%li
					%a{:href => "/privacy_policy/"} Privacy Policy
				%li
					%a{:href => "/help/"} Help
			.clear
			.copyright
				All rights reserved &copy; 
				= "#{Date.today.year} PEMEXAUSA.org"
		.social.fright
			/ <a href="#" ><img src="/img/social1.png"  /></a> <a href="#" ><img src="/img/social2.png"  /></a> <a href="#" ><img src="/img/social3.png"  /></a> <a href="#" ><img src="/img/social4.png"  /></a>
			.madeby
				Website by :
				%a{:href => "#"} EsoKiaLyn Favored Solutions
		.clear

app/views/shared/_header.haml
#header
	- if current_user
		Logged in as: 
		= link_to current_user.name, '/profile'
	.time-auth-search
		.left-tas.fleft
			.pss-time.fleft
				- Time.use_zone("West Central Africa") do |z|
					= Time.zone.now.strftime('%I:%M %p %Z')
				,
				%b PSS
			.usa-time.fleft
				= Time.now.strftime('%I:%M %p %Z')
				,
				%b USA
			.clear
			- if can? :read, :admin #current_user && (current_user.admin? || current_user.super_admin?)
				.fleft
					= link_to 'Admin', admin_home_path
		.search.fright
			.auth.fleft
				- if current_user
					= link_to 'Logout', '/logout', class: 'login-link'
				- else
					-#= link_to "Login",'#loginModal', :data => {:toggle => "modal"}, id: 'show_login_form', class: 'login-link'
					= link_to 'Login', user_session_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#loginModal', :class => 'login-link', 'data-type' => "html" }
			.fleft
				%form{:action => "/search/index.php"}
					%input.search-input.fleft{:name => "q", :onblur => "javascript:if(this.value=='')this.value='Search'", :onfocus => "javascript:if(this.value=='Search')this.value=''", :type => "text", :value => "Search"}/
					%input.search-submit.fleft{:name => "s", :type => "submit", :value => "Search"}/
					.clear
			.clear
		.clear
	- menu_class = current_user ? 'auth-menu' : 'top-menu'
	%div{class: menu_class }
		%table{:cellpadding => "0", :cellspacing => "0", :width => "100%"}
			%tr
				%td{:width => "117"}
					= link_to 'Home', '/', class: "#{ 'selected' if request.path == '/'}"
				%td
					= link_to 'About us', '/about_us', class: "#{ 'selected' if request.path == '/about_us'}"
				%td
					- u = current_user ? 'Members' : 'membership'
					= link_to u, '/membership', class: "#{ 'selected' if request.path == '/membership'}"
				%td
					= link_to 'chapters', '/chapters', class: "#{ 'selected' if request.path == '/chapters'}"
				%td
					= link_to 'projects', '/projects', class: "#{ 'selected' if request.path == '/projects'}"
				%td
					= link_to 'events', '/events', class: "#{ 'selected' if request.path == '/events'}"
				%td
					= link_to 'gallery', '/gallery', class: "#{ 'selected' if request.path == '/gallery'}"
				%td{class: 'donation'}
					- u = current_user ? 'Donors' : 'Donations'
					%a{:href => "/donations/"}= u
				%td
					= link_to 'map', '/map', class: "#{ 'selected' if request.path == '/map'}"
				%td
					= link_to 'profile', '/profile', class: "#{ 'selected' if request.path == '/profile'}"
				%td{:width => "105"}
					= link_to 'convention', '/convention', class: "last #{ 'selected' if request.path == '/convention'}"
	.slide
		%table{:cellpadding => "0", :cellspacing => "0"}
			%tr
				%td.left-slide
					%img{:src => "/assets/logo.jpg"}/
				%td.right-gallery
					#owl-carousel.owl-carousel{style: 'width: 800px;'}
						.item
							%img{:src => "/assets/gallery.jpg"}
						.item
							%img{:src => "/assets/1.jpg"}
						.item
							%img{:src => "/assets/carolinas1.jpg"}
						.item
							%img{:src => "/assets/2.JPG"}
						.item
							%img{:src => "/assets/3.JPG"}
				.clear

app/views/shared/_main_header.haml
!!! Strict
%html{"xml:lang" => "ru", :xmlns => "http://www.w3.org/1999/xhtml"}
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%meta{:content => "PEMEXA, PEMEXA-USA, PSS, PSS Mankon, Mankon, PCC", :name => "keywords"}/
		%meta{:content => "Presbyterian Secondary School Mankon", :name => "description"}/
		%title 
			PemexaUSA : 
			= controller.action_name
		%link{:rel => 'icon', :type => 'image/jpeg', :href => '/favicon.ico'}
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		

app/views/shared/_user_details.html.haml
%td
	.span3{style: "width: 100%;"}
		.reg-col
			Personal Information
		.admin_panel_inner
			.row-fluid
				%b First Name: 
				= user.first_name
			.row-fluid
				%b Middle Name:
				= user.middle_name
			.row-fluid
				%b Last (or Surname) Name (PSS):
				= user.last_name_pss
			.row-fluid
				%b Last (or Surname) Name (Now):
				= user.last_name_now
			.row-fluid
				%b Class Of:
				= user.class_year
			.row-fluid
				%b Gender:
				= user.gender
			.row-fluid
				%b Created:
				= user.created_at.strftime("%b %d, %Y %H:%M:%S") rescue ''
			.row-fluid
				%b Last Updated:
				= user.updated_at.strftime("%b %d, %Y %H:%M:%S") rescue ''
%td
	.span3{style: "width: 100%;"}
		.reg-col
			Contact Information
		.admin_panel_inner
			.row-fluid
				%b Country:
				= address.country.name rescue ''
			.row-fluid
				%b State:
				= address.state.name rescue ''
			.row-fluid
				%b Address Line 1:
				= address.street1
			.row-fluid
				%b Address Line 2:
				= address.street2
			.row-fluid
				%b City:
				= address.city
			.row-fluid
				%b Zip:
				= address.zip
			.row-fluid
				%b Last Updated:
				= address.updated_at.strftime("%b %d, %Y %H:%M:%S") rescue ''
%td
	.span3{style: "width: 100%;"}
		.reg-col
			Membership Information
		.admin_panel_inner
			.row-fluid
				%b Cell Phone:
				= user.phone
			.row-fluid
				%b Full Time Student:
				= user.full_time_student ? 'Yes' : 'No'
			.row-fluid
				%b Profession:
				= user.profession
			.row-fluid
				%b Chapter:
				= user.chapter.name rescue ''
			.row-fluid
				%b Login:
				= user.username
			.row-fluid
				%b Email:
				= user.email
			.row-fluid
				%b Current Login:
				= user.current_sign_in_at.strftime("%b %d, %Y %H:%M:%S") rescue ''
			.row-fluid
				%b Last Login:
				= user.last_sign_in_at.strftime("%b %d, %Y %H:%M:%S") rescue ''	

app/views/shared/_user_form.html.haml
%td
	.span3
		.reg-col
			Personal Information
		.admin_panel_inner
			.row-fluid
				= f.label 'first_name', 'First Name*', class: "control-label", required: true
				= f.text_field :first_name, tabindex: 1, class: 'span12', maxlength: 20, required: true
			.row-fluid
				= f.label 'middle_name', 'Middle Name', class: "control-label"
				= f.text_field :middle_name, tabindex: 2, class: 'span12', maxlength: 20
			.row-fluid
				= f.label 'last_name_pss', 'Last (or Surname) Name (PSS)*', class: "control-label", required: true
				= f.text_field :last_name_pss, tabindex: 3, class: 'span12', maxlength: 20, required: true
			.row-fluid
				= f.label 'last_name_now', 'Last (or Surname) Name (Now)*', class: "control-label", required: true
				= f.text_field :last_name_now, tabindex: 4, class: 'span12', maxlength: 20, required: true
			.row-fluid
				= f.label 'class_year', 'Class Of', class: "control-label"
				= f.select :class_year, (1983..Date.today.year).to_a, {include_blank: '--Please Select--'}, tabindex: 5, class: 'span12'
			.row-fluid
				= f.label 'gender', 'Gender*', class: "control-label", required: true
				= f.select :gender, ['female', 'male'], {include_blank: '--Please Select--'}, tabindex: 6, class: 'span12', required: true
%td
	.span3
		.reg-col
			Contact Information
		= f.fields_for address do |a|
			.admin_panel_inner
				.row-fluid
					= a.label 'country_id', 'Country*', class: "control-label", required: true
					= a.select :country_id, countries.map{|c| [c.name, c.id]}, {include_blank: '--Please Select--'}, tabindex: 8, class: 'span12', required: true
				.row-fluid
					= a.label 'state_id', 'State*', class: "control-label"
					= a.select :state_id, states.map{|c| [c.name, c.id]}, {include_blank: '--Please Select--'}, tabindex: 9, class: 'span12', required: true
				.row-fluid
					= a.label 'street1', 'Address Line 1*', class: "control-label", required: true
					= a.text_field :street1, tabindex: 10, class: 'span12', maxlength: 30, required: true
				.row-fluid
					= a.label 'street2', 'Address Line 2', class: "control-label"
					= a.text_field :street2, tabindex: 11, class: 'span12', maxlength: 20
				.row-fluid
					= a.label 'city', 'City*', class: "control-label", required: true
					= a.text_field :city, tabindex: 12, class: 'span12', maxlength: 20, required: true
				.row-fluid
					= a.label 'zip', 'Zip*', class: "control-label", required: true
					= a.text_field :zip, tabindex: 13, class: 'span12', maxlength: 20, required: true
%td
	.span3
		.reg-col
			Membership Information
		.admin_panel_inner
			.row-fluid
				= f.label 'phone', 'Cell Phone', class: "control-label"
				= f.text_field :phone, tabindex: 14, class: 'span12', maxlength: 75
			.row-fluid
				= f.label 'full_time_student', 'Full Time Student*', class: "control-label", required: true
				= f.select :full_time_student, [['No', false],['Yes', true]], {include_blank: '--Please Select--'}, tabindex: 15, class: 'span12', required: true
			.row-fluid
				= f.label 'profession', 'Profession', class: "control-label"
				= f.text_area :profession, tabindex: 16, class: 'span12', maxlength: 75
			.row-fluid
				= f.label 'chapter_id', 'Chapter', class: "control-label"
				= f.select :chapter_id, all_chapters.map{|c| [c.name, c.id]}, {include_blank: '--Please Select--'}, tabindex: 17, class: 'span12'
			.row-fluid
				= f.label 'username', 'Login (min. 3 characters)*', class: "control-label", required: true
				= f.text_field :username, tabindex: 18, class: 'span12', minlength: 3, maxlength: 25, required: true
			.row-fluid
				= f.label 'email', 'Email*', class: "control-label", required: true
				= f.text_field :email, tabindex: 19, class: 'span12', maxlength: 75, required: true