config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do 
	  get '/auth', to: 'devise/sessions#new', as: :auth
	  get '/login', to: 'devise/sessions#new', as: :login
	  get '/logout', to: 'devise/sessions#destroy', as: :logout
	  match "/confirm", to: "users/confirmations#confirm", via: [:get, :post, :patch] #as: :confirm
  end
      
  devise_for :users, controllers: {
    users: 'users/sessions',
    :passwords => 'users/passwords',
    :registrations => 'users/registrations',
    :confirmations => 'users/confirmations'
  }
  

   root 'welcome#index'
   get '/', to: 'welcome#:index', as: :home
   get '/profile', to: 'profile#new', as: :profile
   get '/edit_profile', to: 'profile#edit', as: :edit_profile
   put '/edit_profile', to: 'profile#update', as: :update_profile
   get '/change_password', to: 'profile#change_password', as: :change_password
   

   namespace :admin do
   	 get '/', to: 'base#index', as: :home
     resources :chapters
     resources :convention_events
     resources :countries
     resources :members
     resources :payment_purposes
     resources :payments
     resources :photos
     resources :projects
     resources :states
     resources :users
     resources :zips
   end
   get '/:action', to: 'welcome#:action'
   
end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :cities, dependent: :destroy
	has_many :zips, dependent: :destroy
	belongs_to :country
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::BaseController
  expose(:state) {State.find_by_id(params[:id]) || State.new}
  
  # POST /admin/states
  # POST /admin/states.json
  def create
    state.attributes = state_params

    respond_to do |format|
      if state.save
        format.html { redirect_to admin_states_path, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: state }
      else
        format.html { render :new }
        format.json { render json: state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/states/1
  # PATCH/PUT /admin/states/1.json
  def update
    respond_to do |format|
      if state.update(state_params)
        format.html { redirect_to admin_state_path(state), notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: state }
      else
        format.html { render :edit }
        format.json { render json: state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/states/1
  # DELETE /admin/states/1.json
  def destroy
    state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params[:state]
    end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.haml
= form_for @admin_state do |f|
  - if @admin_state.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_state.errors.count, "error")} prohibited this admin_state from being saved:"
      %ul
        - @admin_state.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/admin/states/edit.html.haml
%h1 Editing admin_state

= render 'form'

= link_to 'Show', @admin_state
\|
= link_to 'Back', admin_states_path

app/views/admin/states/index.html.haml
.admin_panel_header
	%h1
		= link_to 'All States', admin_states_path 
		|
		= link_to 'State Details', admin_state_path(state) 
		|
		Listing states
.admin_panel_inner
	%table{id: 'admin_states', style: "width: 100%;"}
	  %thead
	    %tr
	      %th
	      %th
	      %th
	      
	  %tbody
	    - states.each do |admin_state|
	      %tr
	        %td= link_to 'Show', admin_state
	        %td= link_to 'Edit', edit_admin_state_path(admin_state)
	        %td= link_to 'Destroy', admin_state, :method => :delete, :data => { :confirm => 'Are you sure?' }
	
	%br
	
	= link_to 'New State', new_admin_state_path

app/views/admin/states/new.html.haml
%h1 New admin_state

= render 'form'

= link_to 'Back', admin_states_path

app/views/admin/states/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_state_path(@admin_state)
\|
= link_to 'Back', admin_states_path