config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do 
	  get '/auth', to: 'devise/sessions#new', as: :auth
	  get '/login', to: 'devise/sessions#new', as: :login
	  get '/logout', to: 'devise/sessions#destroy', as: :logout
	  match "/confirm", to: "users/confirmations#confirm", via: [:get, :post, :patch] #as: :confirm
  end
      
  devise_for :users, controllers: {
    users: 'users/sessions',
    :passwords => 'users/passwords',
    :registrations => 'users/registrations',
    :confirmations => 'users/confirmations'
  }
  

   root 'welcome#index'
   get '/', to: 'welcome#:index', as: :home
   get '/profile', to: 'profile#new', as: :profile
   get '/edit_profile', to: 'profile#edit', as: :edit_profile
   put '/edit_profile', to: 'profile#update', as: :update_profile
   get '/change_password', to: 'profile#change_password', as: :change_password
   

   namespace :admin do
   	 get '/', to: 'base#index', as: :home
     resources :chapters
     resources :convention_events
     resources :countries
     resources :members
     resources :payment_purposes
     resources :payments
     resources :photos
     resources :projects
     resources :states
     resources :users
     resources :zips
   end
   get '/:action', to: 'welcome#:action'
   
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	belongs_to :president, class_name: User
	has_many :users
	has_many :members
	
	def self.active
		where( active: true )
	end
end

app/controllers/admin/chapters_controller.rb
class Admin::ChaptersController < Admin::BaseController
  expose(:chapter) { Chapter.find(params[:id]) || Chapter.new }
  
  # POST /admin/chapters
  # POST /admin/chapters.json
  def create
    respond_to do |format|
      if chapter.save
        format.html { redirect_to admin_chapters_path, notice: 'Chapter was successfully created.' }
        format.json { render :show, status: :created, location: chapter }
      else
        format.html { render :new }
        format.json { render json: chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/chapters/1
  # PATCH/PUT /admin/chapters/1.json
  def update
    respond_to do |format|
      if chapter.update(chapter_params)
        format.html { redirect_to admin_chapter_path(chapter), notice: 'Chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: chapter }
      else
        format.html { render :edit }
        format.json { render json: chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/chapters/1
  # DELETE /admin/chapters/1.json
  def destroy
    chapter.destroy
    respond_to do |format|
      format.html { redirect_to admin_chapters_url, notice: 'Chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params[:chapter]
    end
end

app/helpers/admin/chapters_helper.rb
module Admin::ChaptersHelper
end

app/views/admin/chapters/_form.html.haml
= form_for chapter do |f|
  - if chapter.errors.any?
    #error_explanation
      %h2= "#{pluralize(chapter.errors.count, "error")} prohibited this chapter from being saved:"
      %ul
        - chapter.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/admin/chapters/edit.html.haml
%h1 Editing chapter

= render 'form'

= link_to 'Show', admin_chapter_path(chapter)
\|
= link_to 'Back', :back

app/views/admin/chapters/index.html.haml
.admin_panel_header
	%h1
		listing chapters
.admin_panel_inner
	%table{id: 'admin_chapters', style: "width: 100%;"}
		%thead
			%tr
				%th= 'Name'
				%th= 'Headquarters'
				%th= 'President'
				%th= 'Action'
				
		%tbody
			- all_chapters.each do |admin_chapter|
				%tr
					%td= admin_chapter.name
					%td= admin_chapter.headquarters
					%td= link_to "#{admin_chapter.president.name rescue ''}", admin_user_path(admin_chapter.president) rescue ''
					%td
						= link_to 'Show', admin_chapter_path(admin_chapter)
						= link_to 'Edit', edit_admin_chapter_path(admin_chapter)
						= link_to 'Destroy', admin_chapter_path(admin_chapter), :method => :delete, :data => { :confirm => 'Are you sure?' }
	
	%br
	
	= link_to 'New Chapter', new_admin_chapter_path

app/views/admin/chapters/new.html.haml
%h1 New Chapter

= render 'form'

= link_to 'Back', admin_chapters_path

app/views/admin/chapters/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_chapter_path(chapter)
\|
= link_to 'Back', admin_chapters_path